export const API_ENDPOINT ='https://localhost:5001';
export const URL_LIST_TASK = 'api/list-task';
export const URL_TASK = 'api/task';
export const URL_PROJECT = 'api/project';

export const API_METHOD_POST = 'POST';
export const API_METHOD_GET = "GET";
export const API_METHOD_DELETE = 'DELETE';
export const API_METHOD_PUT = 'PUT';

export const SHOW_FORM_ADD_LIST_TASK = "SHOW_FORM_ADD_LIST_TASK";
export const HIDE_FORM_ADD_LIST_TASK = "HIDE_FORM_ADD_LIST_TASK";

export const SHOW_FORM_ADD_TASK = "SHOW_FORM_ADD_TASK";
export const HIDE_FORM_ADD_TASK = "HIDE_FORM_ADD_TASK";

export const SHOW_MODAL_DETAIL_TASK = "SHOW_MODAL_DETAIL_TASK";
export const HIDE_MODAL_DETAIL_TASK = "HIDE_MODAL_DETAIL_TASK";

export const SHOW_MODAL_ADD_USER = "SHOW_MODAL_ADD_USER";
export const HIDE_MODAL_ADD_USER = "HIDE_MODAL_ADD_USER";

export const SHOW_MODAL_DEADLINE_TASK = "SHOW_MODAL_DEADLINE_TASK";
export const HIDE_MODAL_DEADLINE_TASK = "HIDE_MODAL_DEADLINE_TASK";

export const SHOW_MODAL_ADD_USER_TASK = "SHOW_MODAL_ADD_USER_TASK";
export const HIDE_MODAL_ADD_USER_TASK = "HIDE_MODAL_ADD_USER_TASK";

export const ADD_LIST_TASK_SUCCESS = "ADD_LIST_TASK_SUCCESS";
export const ADD_LIST_TASK_FAILE = "ADD_LIST_TASK_FAILE";

export const GET_LIST_TASK_SUCCESS = "GET_LIST_TASK_SUCCESS";
export const GET_LIST_TASK_FAILE = "GET_LIST_TASK_FAILE";

export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const ADD_TASK_FAILE = "ADD_TASK_FAILE";

export const EDIT_PROJECT_SUCCESS = "EDIT_PROJECT_SUCCESS";
export const EDIT_PROJECT_FAILE = "EDIT_PROJECT_FAILE";